version: "3.3"
services:
  db:
    image: mysql:8.0.21
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      - ./sql/sql_init_data:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "3307:3306"
    container_name: db
  api:
    image: victorgrubio/idea-rating-api:1.0.0
    build:
      context: .
      args:
        version: "1.0.0"
    env_file:
      - .env
    environment:
      - DATABASE_DRIVER=mysql
      - DATABASE_USER=idearating
      - DATABASE_PASSWORD=idearating
      - DATABASE_NAME=idearatingdb
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3307
      - DATABASE_CONFIG_QUERY=createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - API_PORT=8080
      - PROFILE=dev
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    driver: bridge
