version: "3.3"
services:
  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_DATABASE=idearatingdb
      - MYSQL_USER=idearating
      - MYSQL_PASSWORD=idearating
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      - ./sql/sql_init_data:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "3307:3306"
    container_name: db
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
  api:
    image: victorgrubio/idea-rating-api:1.0.0
    build:
      context: .
      args:
        version: "1.0.0"
    environment:
      - DATABASE_DRIVER=mysql
      - DATABASE_USER=idearating
      - DATABASE_PASSWORD=idearating
      - DATABASE_NAME=idearatingdb
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_CONFIG_QUERY=createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - API_PORT=8080
      - PROFILE=dev
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: on-failure
    depends_on:
      - db
    links:
      - db

volumes:
  db:

networks:
  backend:
    driver: bridge
