spring:
  profiles:
    active: ${PROFILE:test}
---
name: test-YAML
environment: testing
enabled: false
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: test
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:h2:file:./h2_database;
    username: sql
    password: sql
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath*:data.sql
springdoc:
  api-docs:
    path: /api-docs
---
name: dev-YAML
environment: development
enabled: true
server:
  port: ${PORT:8080}
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD:root}
    url: jdbc:${DATABASE_DRIVER:mysql}://${DATABASE_HOST:db}:${DATABASE_PORT:3306}/${DATABASE_NAME}?${DATABASE_CONFIG_QUERY:createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    username: ${DATABASE_USER:root}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
  api-docs:
    path: /api-docs
