-- MySQL Script generated by MySQL Workbench
-- jue 02 sep 2021 14:12:39 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `username` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`username`));


-- -----------------------------------------------------
-- Table `ideas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ideas` ;

CREATE TABLE IF NOT EXISTS `ideas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `evaluation_sentences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `evaluation_sentences` ;

CREATE TABLE IF NOT EXISTS `evaluation_sentences` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NOT NULL,
  `idea_id` BIGINT NOT NULL,
  `evaluation_weight_id` BIGINT NOT NULL,
  `type` ENUM('pro', 'con') NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `user_idea_evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_idea_evaluations` ;

CREATE TABLE IF NOT EXISTS `user_idea_evaluations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `evaluation_sentence_id` BIGINT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `evaluation_weights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `evaluation_weights` ;

CREATE TABLE IF NOT EXISTS `evaluation_weights` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `weight` FLOAT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIME,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));
