-- MySQL Script generated by MySQL Workbench
-- jue 02 sep 2021 12:48:06 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IdeaRatingDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IdeaRatingDB` ;

-- -----------------------------------------------------
-- Schema IdeaRatingDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IdeaRatingDB` ;
USE `IdeaRatingDB` ;

-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`users` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`users` (
  `username` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`ideas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`ideas` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`ideas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`evaluation_sentences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`evaluation_sentences` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`evaluation_sentences` (
  `id` BIGINT NOT NULL,
  `content` VARCHAR(100) NOT NULL,
  `idea_id` BIGINT NOT NULL,
  `evaluation_weight_id` BIGINT NOT NULL,
  `type` ENUM('pro', 'con') NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`user_idea_evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`user_idea_evaluations` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`user_idea_evaluations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `evaluation_sentence_id` BIGINT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`evaluation_weights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`evaluation_weights` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`evaluation_weights` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `weight` FLOAT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIME,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

