-- MySQL Script generated by MySQL Workbench
-- jue 02 sep 2021 12:48:06 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema IdeaRatingDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IdeaRatingDB` ;
USE `IdeaRatingDB` ;

-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`users` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`users` (
  `username` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`username`));


-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`ideas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`ideas` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`ideas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`evaluation_sentences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`evaluation_sentences` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`evaluation_sentences` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NOT NULL,
  `idea_id` BIGINT NOT NULL,
  `evaluation_weight_id` BIGINT NOT NULL,
  `type` ENUM('PRO', 'CON') NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`user_idea_evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`user_idea_evaluations` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`user_idea_evaluations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(128) NOT NULL,
  `evaluation_sentence_id` BIGINT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `IdeaRatingDB`.`evaluation_weights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IdeaRatingDB`.`evaluation_weights` ;

CREATE TABLE IF NOT EXISTS `IdeaRatingDB`.`evaluation_weights` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `weight` FLOAT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));

